from __future__ import print_function

from rapidtest import Result, Test, Case
from solutions.all_oone_data_structure import AllOne

with Test(AllOne, operation=True) as test:
    Case('getMaxKey', Result(''),
         'getMinKey', Result(''),

         'inc', ['a'],
         'getMaxKey', Result('a'),
         'getMinKey', Result('a'),
         'inc', ['b'],
         'inc', ['b'],
         'getMaxKey', Result('b'),
         'getMinKey', Result('a'),
         'dec', ['a'],
         'getMaxKey', Result('b'),
         'getMinKey', Result('b'),
         'dec', ['b'],
         'getMaxKey', Result('b'),
         'getMinKey', Result('b'),
         'dec', ['b'],
         'getMaxKey', Result(''),
         'getMinKey', Result(''),

         'inc', ['a'],
         'inc', ['b'],
         'inc', ['b'],
         'inc', ['c'],
         'inc', ['c'],
         'inc', ['d'],
         'inc', ['d'],
         'inc', ['d'],
         'getMinKey', Result('a'),
         'getMaxKey', Result('d'),
         'inc', ['c'],
         'inc', ['c'],
         'getMaxKey', Result('c'),
         'getMinKey', Result('a'),
         'dec', ['a'],
         'getMaxKey', Result('c'),
         'getMinKey', Result('b'),
         'dec', ['b'],
         'dec', ['b'],
         'getMaxKey', Result('c'),
         'getMinKey', Result('d'),
         'dec', ['c'],
         'dec', ['c'],
         'getMaxKey', Result('d'),
         'getMinKey', Result('c'),
         'dec', ['c'],
         'getMaxKey', Result('d'),
         'getMinKey', Result('c'),
         'dec', ['c'],
         'getMaxKey', Result('d'),
         'getMinKey', Result('d'),
         'dec', ['d'],
         'dec', ['d'],
         'getMaxKey', Result('d'),
         'getMinKey', Result('d'),
         'dec', ['d'],
         'getMaxKey', Result(''),
         'getMinKey', Result(''))
